# Generated by Django 6.0 on 2025-12-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealitem',
            options={'ordering': ['date', 'meal_type']},
        ),
        migrations.AddField(
            model_name='mealitem',
            name='from_template',
            field=models.BooleanField(default=False, help_text='Auto-generated from weekly template'),
        ),
        migrations.CreateModel(
            name='WeeklyMenuTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'meal_type'],
                'unique_together': {('day_of_week', 'meal_type')},
            },
        ),
    ]
